fig, ax = plt.subplot_mosaic([['im_obs', 'im_rea'],['annual_obs', 'annual_rea']], constrained_layout=True, gridspec_kw={'height_ratios':(2,1), 'width_ratios':(1,1)}, figsize=(12,8))
tarcu.obs.season.plot_seasonal(series='t_seasonal_anomaly',vcenter=0, vmin=-5, vmax=5, axis=ax['im_obs'])
ax['annual_obs'].plot(tarcu.obs.season.t_seasonal_anomaly.mean(axis=0).rolling(11,center=True).mean(), c='k', linewidth=2, label='Annual')
ax['annual_obs'].plot(tarcu.obs.season.t_seasonal_anomaly[:91].mean(axis=0).rolling(11,center=True).mean(), label='Fall (SON)', c='#A62F2B')
ax['annual_obs'].plot(tarcu.obs.season.t_seasonal_anomaly[91:181].mean(axis=0).rolling(11,center=True).mean(), label='Winter (DJF)', c='#5483A0')
ax['annual_obs'].plot(tarcu.obs.season.t_seasonal_anomaly[181:273].mean(axis=0).rolling(11,center=True).mean(), label='Spring (MAM)', c='#BACE51')
ax['annual_obs'].plot(tarcu.obs.season.t_seasonal_anomaly[273:365].mean(axis=0).rolling(11,center=True).mean(), label='Summer (JJA)', c='#ECB944')
#ax['annual_obs'].legend(loc='center left', bbox_to_anchor=(1, 0.5))
ax['annual_obs'].sharex(ax['im_obs'])
ax['im_obs'].sharex(ax['annual_obs'])
ax['annual_obs'].set_ylabel('Anomaly\n[$^{o}C$]')
ax['im_obs'].set_title('Temperature Anomaly at Balea Station\nRef. period: 1980-2000')

tarcu.down.season.plot_seasonal(series='t_seasonal_anomaly',vcenter=0, vmin=-5, vmax=5, axis=ax['im_rea'])
ax['annual_rea'].plot(tarcu.down.season.t_seasonal_anomaly.mean(axis=0).rolling(11,center=True).mean(), c='k', linewidth=2, label='Annual')
ax['annual_rea'].plot(tarcu.down.season.t_seasonal_anomaly[:91].mean(axis=0).rolling(11,center=True).mean(), label='Fall (SON)', c='#A62F2B')
ax['annual_rea'].plot(tarcu.down.season.t_seasonal_anomaly[91:181].mean(axis=0).rolling(11,center=True).mean(), label='Winter (DJF)', c='#5483A0')
ax['annual_rea'].plot(tarcu.down.season.t_seasonal_anomaly[181:273].mean(axis=0).rolling(11,center=True).mean(), label='Spring (MAM)', c='#BACE51')
ax['annual_rea'].plot(tarcu.down.season.t_seasonal_anomaly[273:365].mean(axis=0).rolling(11,center=True).mean(), label='Summer (JJA)', c='#ECB944')
#ax['annual_rea'].legend(loc='center left', bbox_to_anchor=(1, 0.5))
ax['annual_rea'].sharex(ax['im_rea'])
ax['im_rea'].sharex(ax['annual_rea'])
ax['annual_rea'].set_ylabel('Anomaly\n[$^{o}C$]')
ax['annual_obs'].sharey(ax['annual_rea'])
ax['annual_rea'].sharey(ax['annual_obs'])
ax['annual_rea'].set_ylim(-1,2))